### ISSUE TITLE
Highlight - Change background color

### ISSUE THREAD

**Issue by LaurentDumont** [Vimux/Binario#19]
Been digging for a bit I cannot find anything conclusive.

Is there anyway to change the background color of highlight blocks? I'd like something a bit Darker for the default Binario dark theme.

![image](https://user-images.githubusercontent.com/8936473/69471743-d89eb780-0d70-11ea-868f-125772383cf5.png)

I've tried setting the `background-color` in main.css in `pre` or `code` but it doesn't seem to change. Looking at the page source, it seems to set `272822` as the color code but I cannot find any reference to that value in the code.

I'll play around a bit more to see if I can figure it out.

**Comment by LaurentDumont** [comment]
Looks like some JS might be preventing the colors in the CSS from taking over.

Adding 
```

**Comment by Vimux** [comment]
Hi,

> I've tried setting the background-color in main.css in pre or code but it doesn't seem to change. Looking at the page source, it seems to set 272822 as the color code but I cannot find any reference to that value in the code.

Because it's Hugo related thing, the theme has nothing to do with it.

> Not sure if there is a cleaner way to do it.

I think something like this:

1. Set `pygmentsUseClasses = true` in the site config
2. [Generate Syntax Highlighter CSS](https://gohugo.io/content-management/syntax-highlighting/#generate-syntax-highlighter-css)
3. Include syntax CSS file as a custom CSS
4. Make your CSS changes...

Reference: https://gohugo.io/content-management/syntax-highlighting/

**Comment by LaurentDumont** [comment]
Hey Vimux,

Not a problem - I'll close this as it has nothing to do with this awesome theme!
